### ISSUE TITLE
Make UI Bootstrap/Zoneminder Compatible

### ISSUE THREAD

**Issue by newburns** [lbdc/zm-movie#1]
I'm going to do what I can to integrate this into the flat skin of standard zoneminder.
See if they will accept a PR for it, and have it default into the standard ZM install.

It needs to use the DB credentials from the /etc/zm.conf file, too

**Comment by lbdc** [comment]
script uses DB credentials from zm.conf file

**Comment by newburns** [comment]
Cannot be bootstrap compatible if it is integrated with Zonemidner.
Zoneminder uses a templating system
