### ISSUE TITLE
Optimize Mencoder for Multi-core

### ISSUE THREAD

**Issue by newburns** [lbdc/zm-movie#2]
mencoder fully utilizes a single core in multicore environement.

**Comment by lbdc** [comment]
Raymond
I will update the script to use settings from etc/zm/zm.conf (good idea, hadn't thought of that)

I will look into utilizing multicore options as available also (hadn't thought of that either!)

Luc

```
  From: Raymond Burns <notifications@github.com>
```

 To: lbdc/zm-movie zm-movie@noreply.github.com 
 Sent: Monday, March 16, 2015 7:20 PM
 Subject: [zm-movie] Optimize Mencoder for Multi-core (#2)

mencoder fully utilizes a single core in multicore environement.—

**Comment by lbdc** [comment]
added mencoder option to fully utilise cores.
