### ISSUE TITLE
QUESTION: Mencoder vs FFMPEG

### ISSUE THREAD

**Issue by newburns** [lbdc/zm-movie#5]
What was the reasoning for using Mencoder over FFMpeg?
Just wondering why before asking the devs to try and package mencoder with Zoneminder.

**Comment by lbdc** [comment]
The php script makes a text file listing the path to all the images in sequence and calls mencoder Mencoder can use the text file as input for the images but I have not found a way for ffmpeg to use a file as input. FFmpeg also requires consecutive numbering and does not seem to have the functionality for file input. An alternative could be to make symbolic links with consecutive numbering (/tmp/zm_event_00001.jpg -> /usr/share/events...../event 1262.jpg) for every event and use pattern matching as input to ffmpeg. Don't know how well that would work for large movies though. There is a lot of files, especially at high frame rates. If anyone could point me in the right direction for ffmpeg with file input, I'll gladly use it.       From: Raymond Burns notifications@github.com
 To: lbdc/zm-movie zm-movie@noreply.github.com 
 Sent: Thursday, March 19, 2015 9:12 AM
 Subject: [zm-movie] QUESTION: Mencoder vs FFMPEG (#5)

What was the reasoning for using Mencoder over FFMpeg?
Just wondering why before asking the devs to try and package mencoder with Zoneminder. —
