### ISSUE TITLE
Gaps in video results in text file creation error

### ISSUE THREAD

**Issue by newburns** [lbdc/zm-movie#8]
There was no real way to debug it, but if the video records and there are gaps in the video time, the text file is never created.
Not sure if the gap is at the beginning, middle, or end of the time frame selected; but it results in nothing happening.
There is no error is /var/log/messages, but nothing is really called. Also, the text file is created, but it is empty, so there may not be an error in the workflow, but in the text file creation

**Comment by lbdc** [comment]
Unless there is a bug (quite possible), a zero length file usually happens in 'Alarm' mode if there are no alarms or 'All' mode if there are no recordings between time periods requested. This could also happen if the time periods is very short (within bulk frame intervals) the apache2/error.log usually would show an undefined variable An error log would be a nice addition. I can look into that.        From: Raymond Burns notifications@github.com
 To: lbdc/zm-movie zm-movie@noreply.github.com 
 Sent: Thursday, March 19, 2015 12:15 PM
 Subject: [zm-movie] Gaps in video results in text file creation error (#8)

There was no real way to debug it, but if the video records and there are gaps in the video time, the text file is never created.
Not sure if the gap is at the beginning, middle, or end of the time frame selected; but it results in nothing happening.
There is no error is /var/log/messages, but nothing is really called. Also, the text file is created, but it is empty, so there may not be an error in the workflow, but in the text file creation—

**Comment by lbdc** [comment]
Can you verify if this behaviour is gone in latest commit. I added a log which should identify if there were no events found. Text files with zero length means no events found
